name: Android CI Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Setup Android NDK
      uses: nttld/setup-ndk@v1
      with:
        ndk-version: r25b
    
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Install Build Tools and Platform
      run: sdkmanager "platforms;android-26" "build-tools;33.0.1"

    - name: CMake Configure
      run: >
        cmake -B build
        -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_LATEST_HOME/build/cmake/android.toolchain.cmake
        -DANDROID_ABI=arm64-v8a
        -DANDROID_PLATFORM=android-26

    - name: CMake Build
      run: cmake --build build

    - name: Create APK Structure and Copy Library
      run: |
        # Create a new directory to hold all APK contents
        mkdir apk_contents
        # Create the correct 'lib' directory structure inside the new folder
        mkdir -p apk_contents/lib/arm64-v8a
        # Copy the compiled shared library into the correct path
        cp build/libVulkanSnake.so apk_contents/lib/arm64-v8a/
    
    - name: Create AndroidManifest
      run: |
        echo '<?xml version="1.0" encoding="utf-8"?>' > apk_contents/AndroidManifest.xml
        echo '<manifest xmlns:android="http://schemas.android.com/apk/res/android" package="com.example.vulkansnake">' >> apk_contents/AndroidManifest.xml
        echo '    <application android:hasCode="false" android:label="Vulkan Snake">' >> apk_contents/AndroidManifest.xml
        echo '        <activity android:name="android.app.NativeActivity" android:exported="true">' >> apk_contents/AndroidManifest.xml
        echo '            <meta-data android:name="android.app.lib_name" android:value="VulkanSnake" />' >> apk_contents/AndroidManifest.xml
        echo '            <intent-filter>' >> apk_contents/AndroidManifest.xml
        echo '                <action android:name="android.intent.action.MAIN" />' >> apk_contents/AndroidManifest.xml
        echo '                <category android:name="android.intent.category.LAUNCHER" />' >> apk_contents/AndroidManifest.xml
        echo '            </intent-filter>' >> apk_contents/AndroidManifest.xml
        echo '        </activity>' >> apk_contents/AndroidManifest.xml
        echo '    </application>' >> apk_contents/AndroidManifest.xml
        echo '</manifest>' >> apk_contents/AndroidManifest.xml

    - name: Package Unsigned APK
      run: |
        # Change to the new directory
        cd apk_contents
        # Zip all contents of the current directory into the final unsigned APK
        zip -r ../unsigned.apk .

    - name: Generate Debug Key
      run: |
        keytool -genkey -v -keystore debug.keystore -storepass android -alias androiddebugkey -keypass android -keyalg RSA -keysize 2048 -validity 10000 -dname "CN=Android Debug,O=Android,C=US"

    - name: Sign APK
      run: |
        $ANDROID_HOME/build-tools/33.0.1/apksigner sign --ks debug.keystore --ks-pass pass:android --out signed.apk unsigned.apk

    - name: Upload Signed APK
      uses: actions/upload-artifact@v4
      with:
        name: snake-game-signed-apk
        path: signed.apk
