name: Android CI Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Setup Android NDK
      uses: nttld/setup-ndk@v1
      with:
        ndk-version: r25b
    
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Install Build Tools and Platform
      run: sdkmanager "platforms;android-26" "build-tools;33.0.1"

    - name: CMake Configure
      run: >
        cmake -B build
        -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_LATEST_HOME/build/cmake/android.toolchain.cmake
        -DANDROID_ABI=arm64-v8a
        -DANDROID_PLATFORM=android-26

    - name: CMake Build
      run: cmake --build build

    # --- THE FIX: Correctly structure and package the APK ---

    - name: Prepare APK Contents
      run: |
        mkdir -p apk_contents/lib/arm64-v8a
        cp build/libVulkanSnake.so apk_contents/lib/arm64-v8a/

    - name: Create AndroidManifest
      run: |
        echo '<?xml version="1.0" encoding="utf-8"?>' > AndroidManifest.xml
        echo '<manifest xmlns:android="http://schemas.android.com/apk/res/android" package="com.example.vulkansnake">' >> AndroidManifest.xml
        echo '    <uses-sdk android:minSdkVersion="26" android:targetSdkVersion="33" />' >> AndroidManifest.xml
        echo '    <uses-feature android:glEsVersion="0x00020000" android:required="true" />' >> AndroidManifest.xml
        echo '    <uses-feature android:name="android.hardware.vulkan.level" android:version="0" android:required="true" />' >> AndroidManifest.xml
        echo '    <application android:hasCode="false" android:label="Vulkan Snake">' >> AndroidManifest.xml
        echo '        <activity android:name="android.app.NativeActivity" android:exported="true">' >> AndroidManifest.xml
        echo '            <meta-data android:name="android.app.lib_name" android:value="VulkanSnake" />' >> AndroidManifest.xml
        echo '            <intent-filter>' >> AndroidManifest.xml
        echo '                <action android:name="android.intent.action.MAIN" />' >> AndroidManifest.xml
        echo '                <category android:name="android.intent.category.LAUNCHER" />' >> AndroidManifest.xml
        echo '            </intent-filter>' >> AndroidManifest.xml
        echo '        </activity>' >> AndroidManifest.xml
        echo '    </application>' >> AndroidManifest.xml
        echo '</manifest>' >> AndroidManifest.xml

    - name: Package Unsigned APK
      run: |
        # 1. Compile the manifest into the required binary format
        $ANDROID_HOME/build-tools/33.0.1/aapt2 compile --dir . -o compiled_res.zip
        
        # 2. Link the compiled manifest, libraries, and platform files into an APK
        $ANDROID_HOME/build-tools/33.0.1/aapt2 link --proto-format -o unsigned.apk \
          -I $ANDROID_HOME/platforms/android-26/android.jar \
          --manifest AndroidManifest.xml \
          -R compiled_res.zip \
          --no-auto-version
        
        # 3. Add our native library to the APK
        zip -u unsigned.apk -j apk_contents/lib/arm64-v8a/libVulkanSnake.so

    - name: Generate Debug Key
      run: |
        keytool -genkey -v -keystore debug.keystore -storepass android -alias androiddebugkey -keypass android -keyalg RSA -keysize 2048 -validity 10000 -dname "CN=Android Debug,O=Android,C=US"

    - name: Sign APK
      run: |
        $ANDROID_HOME/build-tools/33.0.1/apksigner sign --ks debug.keystore --ks-pass pass:android --out signed.apk unsigned.apk

    - name: Upload Signed APK
      uses: actions/upload-artifact@v4
      with:
        name: snake-game-signed-apk
        path: signed.apk
