name: Android CI Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Setup Android NDK
      uses: nttld/setup-ndk@v1
      with:
        ndk-version: r25b
    
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Install Build Tools and Platform
      run: sdkmanager "platforms;android-26" "build-tools;33.0.1"

    - name: CMake Configure
      run: >
        cmake -B build
        -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_LATEST_HOME/build/cmake/android.toolchain.cmake
        -DANDROID_ABI=arm64-v8a
        -DANDROID_PLATFORM=android-26

    - name: CMake Build
      run: cmake --build build

    - name: Create APK Structure and Copy Library
      run: |
        # Create a separate 'lib' directory at the root level for native libraries
        mkdir -p lib/arm64-v8a
        # Copy the compiled shared library into the new directory
        cp build/libVulkanSnake.so lib/arm64-v8a/
        # Create the 'res' directory for resources and the manifest
        mkdir -p res

    - name: Create AndroidManifest
      run: |
        echo '<?xml version="1.0" encoding="utf-8"?>' > res/AndroidManifest.xml
        echo '<manifest xmlns:android="http://schemas.android.com/apk/res/android" package="com.example.vulkansnake">' >> res/AndroidManifest.xml
        echo '    <application android:hasCode="false" android:label="Vulkan Snake">' >> res/AndroidManifest.xml
        echo '        <activity android:name="android.app.NativeActivity" android:exported="true">' >> res/AndroidManifest.xml
        echo '            <meta-data android:name="android.app.lib_name" android:value="VulkanSnake" />' >> res/AndroidManifest.xml
        echo '            <intent-filter>' >> res/AndroidManifest.xml
        echo '                <action android:name="android.intent.action.MAIN" />' >> res/AndroidManifest.xml
        echo '                <category android:name="android.intent.category.LAUNCHER" />' >> res/AndroidManifest.xml
        echo '            </intent-filter>' >> res/AndroidManifest.xml
        echo '        </activity>' >> res/AndroidManifest.xml
        echo '    </application>' >> res/AndroidManifest.xml
        echo '</manifest>' >> res/AndroidManifest.xml

    - name: Compile Resources
      run: |
        # Compile the manifest into a binary file
        $ANDROID_HOME/build-tools/33.0.1/aapt2 compile res/AndroidManifest.xml -o AndroidManifest.xml.flat
        # Compile any other resources (if you had them)
        # $ANDROID_HOME/build-tools/33.0.1/aapt2 compile --dir res/ -o compiled_res.zip

    - name: Package Unsigned APK
      run: |
        # Create a temporary directory to assemble the APK contents
        mkdir -p unsigned_apk_contents
        # Move the compiled manifest into the temporary directory with its correct name
        mv AndroidManifest.xml.flat unsigned_apk_contents/AndroidManifest.xml
        # Move the native libraries into the correct 'lib' folder inside the temporary directory
        mkdir -p unsigned_apk_contents/lib
        mv lib/arm64-v8a unsigned_apk_contents/lib/
        # Zip the contents of the temporary directory into the final unsigned APK
        cd unsigned_apk_contents
        zip -r ../unsigned.apk .

    - name: Generate Debug Key
      run: |
        keytool -genkey -v -keystore debug.keystore -storepass android -alias androiddebugkey -keypass android -keyalg RSA -keysize 2048 -validity 10000 -dname "CN=Android Debug,O=Android,C=US"

    - name: Sign APK
      run: |
        $ANDROID_HOME/build-tools/33.0.1/apksigner sign --ks debug.keystore --ks-pass pass:android --out signed.apk unsigned.apk

    - name: Upload Signed APK
      uses: actions/upload-artifact@v4
      with:
        name: snake-game-signed-apk
        path: signed.apk
